name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v /home/mm/vsprojects/URL-short/URL-short/main.go

    - name: Test
      run: go test -v /home/mm/vsprojects/URL-short/URL-short/main.go

    - name: Deploy to Netlify
      uses: netlify/deploy-action@v1
      with:
        token: ${{ secrets.NETLIFY_TOKEN }}
        site-id: ${{ secrets.NETLIFY_SITE_ID }}
        build-dir: '/home/mm/vsprojects/URL-short/URL-short'
        functions-dir: './functions'
