name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: debian-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Build and deploy
        uses: netlify/deploy-action@v1
        with:
          token: ${{ secrets.NETLIFY_TOKEN }}
          site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './'
          functions-dir: './functions'
